MotoGallery/MotoGallery/Models/Album.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MotoGallery.Models
{
    public class AlbumModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public ICollection<int> ImagesId { get; set; }
        public ICollection<ImageModel> Images { get; set; }
    }
}

MotoGallery/MotoGallery/Models/Image.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MotoGallery.Models
{
    public class ImageModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public string Extension { get; set; }
        public string Description { get; set; }
        public string Date { get; set; }
        public bool Show { get; set; } = false;
    }
}

MotoGallery/MotoGallery/Controllers/AngularController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MotoGallery.Controllers
{
    public class AngularController : Controller
    {
        // GET: Angular
        public ActionResult Index(string url)
        {
            return View("Index");
        }
    }
}

MotoGallery/MotoGallery/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MotoGallery.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }


    }
}

MotoGallery/MotoGallery/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MotoGallery.Models;
using ORM.Entity;
using ORM;


namespace MotoGallery.Controllers
{
    public class ImageController : Controller
    {

        private EntityModel db = new EntityModel();

        public ImageController()
        {
            var t = db.Images.Where(a => true).ToList();
            var u = db.Albums.Where(a => true).ToList();
        }

        //public JsonResult AddImageAjax(string fileName, string data/*, string extension=".jpeg", int albumId=0*/)
        //{
        //    var dataIndex = data.IndexOf("base64", StringComparison.Ordinal) + 7;
        //    var cleareData = data.Substring(dataIndex);
        //    var fileData = Convert.FromBase64String(cleareData);
        //    var bytes = fileData.ToArray();

        //    var path = GetPathToImg(fileName);
        //    using (var fileStream = System.IO.File.Create(path))
        //    {
        //        fileStream.Write(bytes, 0, bytes.Length);
        //        fileStream.Close();
        //    }

        //    return Json(true, JsonRequestBehavior.AllowGet);
        //}

        public JsonResult AddImageAjax(string fileName, string description, string data, string albumName, string extension)
        {
            if (data == null || fileName == null || albumName == null || extension == null) return Json(false, JsonRequestBehavior.AllowGet);

            var dataIndex = data.IndexOf("base64", StringComparison.Ordinal) + 7;
            var cleareData = data.Substring(dataIndex);
            var fileData = Convert.FromBase64String(cleareData);
            var bytes = fileData.ToArray();

            var path = GetPathToImg($"{fileName}.{extension}");

            if (System.IO.File.Exists(path)) throw new FileLoadException("File alredy exist", $"{fileName}.{extension}");

            using (var fileStream = System.IO.File.Create(path))
            {
                fileStream.Write(bytes, 0, bytes.Length);
                fileStream.Close();
            }

            var album = db.Albums.FirstOrDefault(a => a.Name == albumName);
            if (album == null)
            {
                album = new Album()
                {
                    Name = albumName,
                    User = db.Users.FirstOrDefault() //Must be current user
                };
                db.Albums.Add(album);
                db.SaveChanges();
                album = db.Albums.FirstOrDefault(a => a.Name == albumName);
            }

            var tempImg = new Image()
            {
                Album = album,
                AlbumId = album.Id,
                CreationDate = DateTime.Now,
                Desc = description,
                Path = Path.Combine("Content", "img", $"{fileName}.{extension}"),
                UserId = db.Users.FirstOrDefault().Id,
                Name = fileName
            };
            db.Images.Add(tempImg);
            db.SaveChanges();
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        //[HttpPost]
        //public JsonResult RemoveImage(string url)
        //{
        //    var imgName = Path.GetFileName(url);
        //    System.IO.File.Delete(GetPathToImg(imgName));
        //    return Json(true, JsonRequestBehavior.AllowGet);
        //}

        [HttpPost]
        public JsonResult RemoveImage(int id)
        {
            var image = db.Images.FirstOrDefault(i => i.Id == id);
            db.Images.Remove(image);
            System.IO.File.Delete(Path.Combine(Server.MapPath("~"), image.Path));
            db.SaveChanges();
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetAlbums()
        {
            var albums = db.Albums.Where(a => true).ToList();

            List<Image> allImages = new List<Image>();
            foreach (Album album in albums)
            {
                if (album.Images != null)
                allImages.AddRange(album.Images);
            }

            albums.Add(new Album() { Id = 0, Name = "All Images", Images = allImages });

            var jsonAlbums = albums.Select(delegate (Album a)
              {
                  var ext = GetAlbumExtentions(a);

                  return new
                  {
                      Id = a.Id,
                      Name = a.Name,
                      Extensions = ext
                  };
              }).OrderBy(a=>a.Id).ToList();

     
           
            return Json(jsonAlbums, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetImages()
        {
            var imageFiles = db.Images.Where(z => true).ToList();
            var imges = imageFiles.Select(BuildImage);
            return Json(imges, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult GetImagesFromAlbum(int id)
        {
            if (id == 0)
            {
                return GetImages();
            }


            var alb = db.Albums.FirstOrDefault(a => a.Id == id);
            var imageFiles = alb.Images;
            if (imageFiles == null) return GetImages();
            var imges = imageFiles.Select(BuildImage);
            return Json(imges, JsonRequestBehavior.AllowGet);
        }



        private string GetPathToImg(string fileName)
        {
            var serverPath = Server.MapPath("~");
            return Path.Combine(serverPath, "Content", "img", fileName);
        }

        private ImageModel BuildImage(Image image)
        {
            var serverPath = Server.MapPath("~");
            ;
            var imageTemp = new ImageModel()
            {
                Id = image.Id,
                Url = Url.Content(Path.Combine("~", image.Path)),
                Name = image.Name,
                Extension = Path.GetExtension(image.Path),
                Date = image.CreationDate.Value.ToShortDateString(),
                Description= image.Desc
            };
            return imageTemp;
        }

        private List<string> GetAlbumExtentions(Album a)
        {
            List<string> temp = new List<string>(); ;

            if (a.Images != null) { 
                foreach (Image img in a.Images)
            {
                var ext = Path.GetExtension(img.Path);
                if (!temp.Contains(ext)) { temp.Add(ext); }
            };
            };
            return temp;
        }
    }

}

MotoGallery/MotoGallery/Views/Angular/Index.cshtml

<!DOCTYPE html>
<html ng-app="gallery">
<head>
    <base href="/" />
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <script src="~/Scripts/angular.js"></script>
    <script src="~/Scripts/_appScript.js"></script>
    <script src="~/Scripts/angular-route.js"></script>
    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <link rel="shortcut icon" href="../../assets/ico/favicon.ico">


    <title>MotocyleGallery</title>

    <!-- Bootstrap core CSS -->
    <!-- Latest compiled and minified CSS -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />

</head>

<body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Moto Gallery", "gallery", "Angular", null, new { @class = "navbar-brand" })
                @Html.ActionLink("Add Image", "addImg", "Angular", null, new { @class = "navbar-brand" })
                @Html.ActionLink("About", "About", "Angular", null, new { @class = "navbar-brand" })

            </div>
            <div class="navbar-collapse collapse">
                <form class="navbar-form navbar-right" role="form">
                    <div class="form-group">
                        <input type="text" placeholder="Email" class="form-control">
                    </div>
                    <div class="form-group">
                        <input type="password" placeholder="Password" class="form-control">
                    </div>
                    <button type="submit" class="btn btn-success">Sign in</button>
                </form>
            </div><!--/.navbar-collapse -->
        </div>
    </div>

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">

        <div class="container">
            <!-- Example row of columns -->
            <div class="row">

            </div>
            <div ng-view>Loading...</div>
            <hr>

            <footer>
                <p>&copy; EPAM.RD.2017F.Lipinskiy</p>
            </footer>
        </div> <!-- /container -->
        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
    </div>
</body>
</html>











